version: '3.8'

services:
  insightface-gpu:
    build: .
    image: insightface-gpu:cuda12.6-py310
    container_name: insightface-gpu-container
    volumes:
      - ./models:/app/models:ro  
      - ./pair:/app/pair:ro     
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
